"""Add notifications

Revision ID: 26f2430df8fb
Revises: 8d4da1c4dc51
Create Date: 2026-08-04 06:27:08.145039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26f2430df8fb'
down_revision: Union[str, Sequence[str], None] = '8d4da1c4dc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered_channels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_user_id'), 'notification_events', ['user_id'], unique=False)
    op.add_column('calendar_events', sa.Column('reminded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('reminded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('web_push_subscription', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('notify_email', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('notify_web_push', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('notify_telegram', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_telegram')
    op.drop_column('users', 'notify_web_push')
    op.drop_column('users', 'notify_email')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'web_push_subscription')
    op.drop_column('tasks', 'reminded')
    op.drop_column('calendar_events', 'reminded')
    op.drop_index(op.f('ix_notification_events_user_id'), table_name='notification_events')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
