"""Add Habit model

Revision ID: 412992a719b1
Revises: 2863618fd473
Create Date: 2026-08-08 00:34:30.724830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '412992a719b1'
down_revision: Union[str, Sequence[str], None] = '2863618fd473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('habit_type', sa.Enum('Daily', 'LongTerm', 'Recurring', 'Flexible', name='habittype'), nullable=False),
    sa.Column('suggestion_trigger', sa.String(length=255), nullable=True),
    sa.Column('status_text', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.String(length=255), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('last_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.drop_index(op.f('memories_hnsw_idx'), table_name='memories', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('memories_text_lemmatized_idx'), table_name='memories', postgresql_using='gin')
    op.drop_table('memories')
    op.add_column('conversations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_column('conversations', 'project_id')
    op.create_table('memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('memories_pkey'))
    )
    op.create_index(op.f('memories_text_lemmatized_idx'), 'memories', [sa.literal_column("to_tsvector('simple'::regconfig, payload ->> 'text_lemmatized'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('memories_hnsw_idx'), 'memories', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
