"""Remove finance categories

Revision ID: 80d154f2832b
Revises: e51228c11a37
Create Date: 2026-08-08 01:03:55.176020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80d154f2832b'
down_revision: Union[str, Sequence[str], None] = 'e51228c11a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', postgresql.ENUM('Food', 'Travel', 'Shopping', 'Health', 'Education', 'Business', 'Entertainment', 'Bills', 'Rent', 'Salary', 'Freelance', 'Other', name='transactioncategory'), autoincrement=False, nullable=False))
    op.create_table('budgets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('Food', 'Travel', 'Shopping', 'Health', 'Education', 'Business', 'Entertainment', 'Bills', 'Rent', 'Salary', 'Freelance', 'Other', name='transactioncategory'), autoincrement=False, nullable=False),
    sa.Column('monthly_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('budgets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('budgets_pkey'))
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    # ### end Alembic commands ###
