"""Add WhatsApp fields

Revision ID: e1c93c982daa
Revises: 26f2430df8fb
Create Date: 2026-08-04 08:37:19.765857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c93c982daa'
down_revision: Union[str, Sequence[str], None] = '26f2430df8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('notify_whatsapp', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('whatsapp_window_start', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_window_start')
    op.drop_column('users', 'notify_whatsapp')
    op.drop_column('users', 'whatsapp_phone_number')
    # no downgrade for memories
    # ### end Alembic commands ###
