"""Add Finance models and TaskCategory

Revision ID: e51228c11a37
Revises: 412992a719b1
Create Date: 2026-08-08 00:49:09.377675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e51228c11a37'
down_revision: Union[str, Sequence[str], None] = '412992a719b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('Food', 'Travel', 'Shopping', 'Health', 'Education', 'Business', 'Entertainment', 'Bills', 'Rent', 'Salary', 'Freelance', 'Other', name='transactioncategory'), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.Enum('Income', 'Expense', 'Transfer', 'Savings', 'Receivable', 'Payable', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('Food', 'Travel', 'Shopping', 'Health', 'Education', 'Business', 'Entertainment', 'Bills', 'Rent', 'Salary', 'Freelance', 'Other', name='transactioncategory'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_index(op.f('memories_hnsw_idx'), table_name='memories', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('memories_text_lemmatized_idx'), table_name='memories', postgresql_using='gin')
    op.drop_table('memories')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.add_column('conversations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'])
    taskcategory = postgresql.ENUM('Necessities', 'College', 'Business', 'FRKProductions', 'Finance', 'Health', 'Learning', 'Content', 'Social', 'Household', 'Creative', 'Wellbeing', 'Travel', 'Maintenance', 'Growth', 'Uncategorized', name='taskcategory')
    taskcategory.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('category', taskcategory, nullable=False, server_default='Uncategorized'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_column('conversations', 'project_id')
    op.create_table('habits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('habit_type', postgresql.ENUM('Daily', 'LongTerm', 'Recurring', 'Flexible', name='habittype'), autoincrement=False, nullable=False),
    sa.Column('suggestion_trigger', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('progress', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('streak_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_completed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('habits_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('habits_pkey'))
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('memories_pkey'))
    )
    op.create_index(op.f('memories_text_lemmatized_idx'), 'memories', [sa.literal_column("to_tsvector('simple'::regconfig, payload ->> 'text_lemmatized'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('memories_hnsw_idx'), 'memories', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
